import { useCallback, useEffect, useState, type FormEvent } from 'react';
import Modal from '../components/Modal';
import PermissionGate from '../components/PermissionGate';
import { adminService, type CourseInput } from '../services/admin.service';
import { errorMessage } from '../services/api';
import type { Course, Enrollment } from '../types';
const blank: CourseInput = { name: '', category: '', instructor: '', shortDescription: '', description: '', tuition: 0, capacity: 1, isPublished: true };
export default function CoursesPage() {
 const [items,setItems]=useState<Course[]>([]),[total,setTotal]=useState(0),[search,setSearch]=useState(''),[published,setPublished]=useState(''); const [editing,setEditing]=useState<Course|'new'|null>(null),[form,setForm]=useState<CourseInput>(blank),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''); const [rosterCourse,setRosterCourse]=useState<Course|null>(null),[roster,setRoster]=useState<Enrollment[]>([]),[rosterBusy,setRosterBusy]=useState(false);
 const load=useCallback(async()=>{try{const page=await adminService.courses({limit:100,...(search&&{search}),...(published&&{isPublished:published==='true'})});setItems(page.items);setTotal(page.total);}catch(e){setError(errorMessage(e));}},[search,published]); useEffect(()=>{const timer=window.setTimeout(()=>void load(),350);return()=>window.clearTimeout(timer);},[load]);
 function open(course?:Course){setEditing(course||'new');setForm(course?{name:course.name,category:course.category,instructor:course.instructor,shortDescription:course.shortDescription,description:course.description,tuition:course.tuition,capacity:course.capacity,isPublished:course.isPublished}:{...blank});setError('');}
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{if(editing==='new')await adminService.createCourse(form);else if(editing)await adminService.updateCourse(editing.code,form);setNotice(editing==='new'?'Đã tạo khóa học.':'Đã cập nhật khóa học.');setEditing(null);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function remove(course:Course){if(!confirm(`Xóa khóa học “${course.name}”?`))return;try{await adminService.deleteCourse(course.code);setNotice('Đã xóa khóa học.');await load();}catch(e){setError(errorMessage(e));}}
 async function openRoster(course:Course){setRosterCourse(course);setRosterBusy(true);setError('');try{setRoster((await adminService.courseEnrollments(course.code)).items);}catch(e){setError(errorMessage(e));setRoster([]);}finally{setRosterBusy(false);}}
 return <><div className="page-heading"><div><p className="eyebrow">ĐÀO TẠO</p><h1>Quản lý khóa học</h1><p>{total} khóa học</p></div><PermissionGate permission="courses:write"><button className="primary-button" onClick={()=>open()}>＋ Thêm khóa học</button></PermissionGate></div><div className="toolbar"><input aria-label="Tìm khóa học" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm tên khóa học…"/><select value={published} onChange={e=>setPublished(e.target.value)}><option value="">Tất cả trạng thái</option><option value="true">Đang hiển thị</option><option value="false">Đang ẩn</option></select></div>{error&&<p className="alert error">{error}</p>}{notice&&<p className="alert success">{notice}</p>}
 <div className="table-card"><table><thead><tr><th>Khóa học</th><th>Giảng viên</th><th>Học phí</th><th>Sĩ số</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{items.map(c=><tr key={c.code}><td><strong>{c.name}</strong><small>{c.category}</small></td><td>{c.instructor}</td><td>{c.tuition.toLocaleString('vi-VN')} ₫</td><td>{c.enrolledCount}/{c.capacity}</td><td><span className={`badge ${c.isPublished?'active':'muted'}`}>{c.isPublished?'Hiển thị':'Đang ẩn'}</span></td><td><div className="row-actions"><button onClick={()=>void openRoster(c)}>Học viên</button><PermissionGate permission="courses:write"><button onClick={()=>open(c)}>Sửa</button></PermissionGate><PermissionGate permission="courses:delete"><button className="danger" onClick={()=>void remove(c)}>Xóa</button></PermissionGate></div></td></tr>)}</tbody></table>{!items.length&&<p className="empty">Không có khóa học phù hợp.</p>}</div>
 {editing&&<Modal title={editing==='new'?'Thêm khóa học':'Cập nhật khóa học'} onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={submit}><label className="span-2">Tên khóa học<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Danh mục<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} required/></label><label>Giảng viên<input value={form.instructor} onChange={e=>setForm({...form,instructor:e.target.value})} required/></label><label>Học phí<input type="number" min="0" value={form.tuition} onChange={e=>setForm({...form,tuition:Number(e.target.value)})} required/></label><label>Sức chứa<input type="number" min="1" value={form.capacity} onChange={e=>setForm({...form,capacity:Number(e.target.value)})} required/></label><label className="span-2">Mô tả ngắn<textarea value={form.shortDescription} onChange={e=>setForm({...form,shortDescription:e.target.value})} required/></label><label className="span-2">Mô tả chi tiết<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><label className="check span-2"><input type="checkbox" checked={form.isPublished} onChange={e=>setForm({...form,isPublished:e.target.checked})}/> Hiển thị cho học viên</label><div className="modal-actions span-2"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>Hủy</button><button className="primary-button" disabled={busy}>{busy?'Đang lưu…':'Lưu'}</button></div></form></Modal>}
 {rosterCourse&&<Modal title={`Học viên · ${rosterCourse.name}`} onClose={()=>setRosterCourse(null)}>{rosterBusy?<p className="empty">Đang tải học viên…</p>:roster.length?<div className="roster-list">{roster.map(item=><div key={item.code}><div><strong>{item.student.fullName}</strong><small>{item.student.email}</small></div><div><span className={`badge ${item.status==='ENROLLED'?'active':'muted'}`}>{item.status==='ENROLLED'?'Đang học':'Đã hủy'}</span><small>{item.enrolledDate}</small></div></div>)}</div>:<p className="empty">Khóa học chưa có học viên.</p>}</Modal>}</>;
}
