import { useCallback, useEffect, useState, type FormEvent } from 'react';
import Modal from '../components/Modal';
import PermissionGate from '../components/PermissionGate';
import { adminService, type CategoryItem, type CourseInput } from '../services/admin.service';
import { errorMessage } from '../services/api';
import type { Course, Enrollment } from '../types';
import { uploadImage } from '../services/upload.service';
import { showToast } from '../components/Toast';
import Loading from '../components/Loading';
import { useConfirm } from '../hooks/useConfirm';
const blank: CourseInput = { name: '', categoryCode: '', instructor: '', shortDescription: '', description: '', tuition: 0, capacity: 1, isPublished: true };
export default function CoursesPage() {
 const {confirmAction,confirmModal}=useConfirm();
 const [items,setItems]=useState<Course[]>([]),[categories,setCategories]=useState<CategoryItem[]>([]),[total,setTotal]=useState(0),[search,setSearch]=useState(''),[published,setPublished]=useState(''); const [editing,setEditing]=useState<Course|'new'|null>(null),[viewing,setViewing]=useState<Course|null>(null),[form,setForm]=useState<CourseInput>(blank),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''); const [rosterCourse,setRosterCourse]=useState<Course|null>(null),[roster,setRoster]=useState<Enrollment[]>([]),[rosterBusy,setRosterBusy]=useState(false); const [newCategoryName,setNewCategoryName]=useState(''),[managingCategories,setManagingCategories]=useState(false),[categoryBusy,setCategoryBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const [page,categoryItems]=await Promise.all([adminService.courses({limit:100,...(search&&{search}),...(published&&{isPublished:published==='true'})}),adminService.categories()]);setItems(page.items);setTotal(page.total);setCategories(categoryItems);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}},[search,published]); useEffect(()=>{const timer=window.setTimeout(()=>void load(),350);return()=>window.clearTimeout(timer);},[load]);
 function open(course?:Course){setEditing(course||'new');setNewCategoryName('');setForm(course?{name:course.name,categoryCode:course.categoryCode,instructor:course.instructor,shortDescription:course.shortDescription,description:course.description,tuition:course.tuition,capacity:course.capacity,isPublished:course.isPublished,imageUrl:course.imageUrl}:{...blank});setError('');}
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{let input=form;if(form.categoryCode==='__new__'){const category=await adminService.createCategory(newCategoryName);input={...form,categoryCode:category.code};}if(editing==='new')await adminService.createCourse(input);else if(editing)await adminService.updateCourse(editing.code,input);const message=editing==='new'?'Đã tạo khóa học.':'Đã cập nhật khóa học.';setNotice(message);showToast(message);setEditing(null);await load();}catch(e){const message=errorMessage(e);setError(message);showToast(message,'error');}finally{setBusy(false);}}
 async function remove(course:Course){if(!await confirmAction({title:'Xác nhận xóa khóa học',message:`Bạn có chắc muốn xóa khóa học “${course.name}”?`,confirmLabel:'Xóa khóa học',danger:true}))return;try{await adminService.deleteCourse(course.code);setNotice('Đã xóa khóa học.');await load();}catch(e){setError(errorMessage(e));}}
 async function removeCategory(category:CategoryItem){if(!await confirmAction({title:'Xác nhận xóa danh mục',message:`Bạn có chắc muốn xóa danh mục “${category.name}”?`,confirmLabel:'Xóa danh mục',danger:true}))return;setCategoryBusy(true);try{await adminService.deleteCategory(category.code);showToast('Đã xóa danh mục.');await load();}catch(e){const message=errorMessage(e);setError(message);showToast(message,'error');}finally{setCategoryBusy(false);}}
 async function openRoster(course:Course){setRosterCourse(course);setRosterBusy(true);setError('');try{setRoster((await adminService.courseEnrollments(course.code)).items);}catch(e){setError(errorMessage(e));setRoster([]);}finally{setRosterBusy(false);}}
 return <><div className="page-heading"><div><p className="eyebrow">ĐÀO TẠO</p><h1>Quản lý khóa học</h1><p>{total} khóa học</p></div><PermissionGate permission="courses:write"><div className="heading-actions"><button className="secondary-button" onClick={()=>setManagingCategories(true)}>Quản lý danh mục</button><button className="primary-button" onClick={()=>open()}>＋ Thêm khóa học</button></div></PermissionGate></div><div className="toolbar"><input aria-label="Tìm khóa học" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm tên khóa học…"/><select value={published} onChange={e=>setPublished(e.target.value)}><option value="">Tất cả trạng thái</option><option value="true">Đang hiển thị</option><option value="false">Đang ẩn</option></select></div>{error&&<p className="alert error">{error}</p>}{notice&&<p className="alert success">{notice}</p>}
 {loading?<Loading/>:<div className="table-card"><table><thead><tr><th>Khóa học</th><th>Giảng viên</th><th>Học phí</th><th>Sĩ số</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{items.map(c=><tr key={c.code}><td><strong>{c.name}</strong><small>{c.category}</small></td><td>{c.instructor}</td><td>{c.tuition.toLocaleString('vi-VN')} ₫</td><td>{c.enrolledCount}/{c.capacity}</td><td><span className={`badge ${c.isPublished?'active':'muted'}`}>{c.isPublished?'Hiển thị':'Đang ẩn'}</span></td><td><div className="row-actions"><button onClick={()=>setViewing(c)}>Xem chi tiết</button><button onClick={()=>void openRoster(c)}>Học viên</button><PermissionGate permission="courses:write"><button onClick={()=>open(c)}>Sửa</button></PermissionGate><PermissionGate permission="courses:delete"><button className="danger" onClick={()=>void remove(c)}>Xóa</button></PermissionGate></div></td></tr>)}</tbody></table>{!items.length&&<p className="empty">Không có khóa học phù hợp.</p>}</div>}
 {viewing&&<Modal title="Chi tiết khóa học" onClose={()=>setViewing(null)}><div className="detail-grid">{viewing.imageUrl&&<img className="course-image-preview span-2" src={viewing.imageUrl} alt={viewing.name}/>}<div><small>Mã khóa học</small><strong>{viewing.code}</strong></div><div><small>Trạng thái</small><strong>{viewing.isPublished?'Đang hiển thị':'Đang ẩn'}</strong></div><div><small>Tên khóa học</small><strong>{viewing.name}</strong></div><div><small>Danh mục</small><strong>{viewing.category}</strong></div><div><small>Giảng viên</small><strong>{viewing.instructor}</strong></div><div><small>Học phí</small><strong>{viewing.tuition.toLocaleString('vi-VN')} ₫</strong></div><div><small>Sĩ số</small><strong>{viewing.enrolledCount}/{viewing.capacity}</strong></div><div className="span-2"><small>Mô tả</small><p>{viewing.description}</p></div></div></Modal>}
 {editing&&<Modal title={editing==='new'?'Thêm khóa học':'Cập nhật khóa học'} onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={submit}><label className="span-2">Tên khóa học<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Danh mục<select value={form.categoryCode} onChange={e=>{setForm({...form,categoryCode:e.target.value});if(e.target.value!=='__new__')setNewCategoryName('');}} required><option value="">Chọn danh mục</option>{categories.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}<option value="__new__">Nhập mới</option></select>{form.categoryCode==='__new__'&&<input className="category-new-input" value={newCategoryName} onChange={e=>setNewCategoryName(e.target.value)} placeholder="Nhập mới" maxLength={80} required autoFocus/>}</label><label>Giảng viên<input value={form.instructor} onChange={e=>setForm({...form,instructor:e.target.value})} required/></label><label>Học phí<input type="number" min="0" value={form.tuition} onChange={e=>setForm({...form,tuition:Number(e.target.value)})} required/></label><label>Sức chứa<input type="number" min="1" value={form.capacity} onChange={e=>setForm({...form,capacity:Number(e.target.value)})} required/></label><label className="span-2">Mô tả ngắn<textarea value={form.shortDescription} onChange={e=>setForm({...form,shortDescription:e.target.value})} required/></label><label className="span-2">Mô tả chi tiết<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><label className="span-2">Ảnh khóa học<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);try{const imageUrl=await uploadImage(file);setForm({...form,imageUrl});showToast('Tải ảnh khóa học thành công.');}catch(reason){const message=errorMessage(reason);setError(message);showToast(message,'error');}finally{setUploading(false);}}}/>{uploading&&<span className="upload-progress"><span className="spinner"/>Đang tải ảnh…</span>}</label><div className="image-preview-frame span-2">{form.imageUrl?<img className="course-image-preview" src={form.imageUrl} alt="Ảnh khóa học"/>:<span>Ảnh xem trước</span>}</div><label className="check span-2"><input type="checkbox" checked={form.isPublished} onChange={e=>setForm({...form,isPublished:e.target.checked})}/> Hiển thị cho học viên</label><div className="modal-actions span-2"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>Hủy</button><button className="primary-button" disabled={busy||uploading}>{busy?'Đang lưu…':'Lưu'}</button></div></form></Modal>}
 {managingCategories&&<Modal title="Quản lý danh mục" onClose={()=>setManagingCategories(false)}><div className="category-list">{categories.map(category=><div key={category.code}><span>{category.name}</span><PermissionGate permission="courses:delete"><button type="button" className="danger" disabled={categoryBusy} onClick={()=>void removeCategory(category)}>Xóa</button></PermissionGate></div>)}{!categories.length&&<p className="empty">Chưa có danh mục.</p>}</div></Modal>}
 {rosterCourse&&<Modal title={`Học viên · ${rosterCourse.name}`} onClose={()=>setRosterCourse(null)}>{rosterBusy?<p className="empty">Đang tải học viên…</p>:roster.length?<div className="roster-list">{roster.map(item=><div key={item.code}><div><strong>{item.student.fullName}</strong><small>{item.student.email}</small></div><div><span className={`badge ${item.status==='ENROLLED'?'active':'muted'}`}>{item.status==='ENROLLED'?'Đang học':'Đã hủy'}</span><small>{item.enrolledDate}</small></div></div>)}</div>:<p className="empty">Khóa học chưa có học viên.</p>}</Modal>}{confirmModal}</>;
}
