import { useCallback, useEffect, useState, type FormEvent } from 'react';
import Modal from '../components/Modal';
import PermissionGate from '../components/PermissionGate';
import { adminService, type UserInput } from '../services/admin.service';
import { errorMessage } from '../services/api';
import type { Role, User } from '../types';

type EditInput = Omit<UserInput, 'password'>;
const blank: UserInput = { fullName: '', email: '', password: '', role: 'STUDENT', isActive: true };

export default function UsersPage() {
  const [items, setItems] = useState<User[]>([]); const [total, setTotal] = useState(0); const [selected, setSelected] = useState<string[]>([]);
  const [search, setSearch] = useState(''); const [role, setRole] = useState(''); const [active, setActive] = useState('');
  const [editing, setEditing] = useState<User | 'new' | null>(null); const [viewing, setViewing] = useState<User | null>(null); const [form, setForm] = useState<UserInput>(blank);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { try { setError(''); const page = await adminService.users({ limit: 100, ...(search.trim() && { search: search.trim() }), ...(role && { role }), ...(active && { isActive: active }) }); setItems(page.items); setTotal(page.total); setSelected(current => current.filter(code => page.items.some(item => item.code === code))); } catch (reason) { setError(errorMessage(reason)); } }, [search, role, active]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 350); return () => window.clearTimeout(timer); }, [load]);
  function open(user?: User) { setEditing(user || 'new'); setForm(user ? { fullName: user.fullName, email: user.email, role: user.role, isActive: user.isActive } : { ...blank }); setError(''); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { if (editing === 'new') await adminService.createUser(form); else if (editing) { const { fullName, email, role, isActive } = form as EditInput; await adminService.updateUser(editing.code, { fullName, email, role, isActive }); } setEditing(null); await load(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } }
  async function remove(user: User) { if (!confirm(`Xóa tài khoản ${user.email}?`)) return; try { await adminService.deleteUser(user.code); await load(); } catch (reason) { setError(errorMessage(reason)); } }
  async function removeSelected() { if (!selected.length || !confirm(`Xóa ${selected.length} tài khoản đã chọn?`)) return; setBusy(true); try { await adminService.deleteUsers(selected); setSelected([]); await load(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } }
  async function toggleLock(user: User) { const action = user.isActive ? 'khóa' : 'mở khóa'; if (!confirm(`${action.charAt(0).toUpperCase() + action.slice(1)} tài khoản ${user.email}?`)) return; try { await adminService.updateUser(user.code, { isActive: !user.isActive }); await load(); } catch (reason) { setError(errorMessage(reason)); } }
  async function resetPassword(user: User) { if (!confirm(`Tạo mật khẩu mới và gửi đến ${user.email}?`)) return; setBusy(true); setNotice(''); try { const result = await adminService.resetUserPassword(user.code); setNotice(result.message); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } }
  const allSelected = items.length > 0 && items.every(item => selected.includes(item.code));
  return <><div className="page-heading"><div><p className="eyebrow">TÀI KHOẢN</p><h1>Quản lý người dùng</h1><p>{total} tài khoản trong hệ thống</p></div><PermissionGate permission="users:write"><button className="primary-button" onClick={() => open()}>＋ Thêm người dùng</button></PermissionGate></div>
    <div className="filter-panel"><div className="filter-title"><span>☷</span><strong>Bộ lọc</strong></div><div className="toolbar users-toolbar"><input aria-label="Tìm người dùng" value={search} onChange={e => setSearch(e.target.value)} placeholder="Tìm theo tên hoặc email…" /><select aria-label="Lọc vai trò" value={role} onChange={e => setRole(e.target.value)}><option value="">Tất cả vai trò</option><option>ADMIN</option><option>STUDENT</option></select><select aria-label="Lọc trạng thái" value={active} onChange={e => setActive(e.target.value)}><option value="">Tất cả trạng thái</option><option value="true">Đang hoạt động</option><option value="false">Đã khóa</option></select></div></div>
    {selected.length > 0 && <div className="bulk-bar"><span>Đã chọn {selected.length} tài khoản</span><PermissionGate permission="users:delete"><button className="danger-button" disabled={busy} onClick={() => void removeSelected()}>Xóa đã chọn</button></PermissionGate></div>}
    {error && <p className="alert error">{error}</p>}{notice && <p className="alert success">{notice}</p>}
    <div className="table-card"><table><thead><tr><th className="check-cell"><input type="checkbox" aria-label="Chọn tất cả" checked={allSelected} onChange={e => setSelected(e.target.checked ? items.map(item => item.code) : [])} /></th><th>Người dùng</th><th>Vai trò</th><th>Trạng thái</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody>{items.map(user => <tr key={user.code}><td className="check-cell"><input type="checkbox" aria-label={`Chọn ${user.email}`} checked={selected.includes(user.code)} onChange={e => setSelected(current => e.target.checked ? [...current, user.code] : current.filter(code => code !== user.code))} /></td><td><strong>{user.fullName}</strong><small>{user.email}</small></td><td><span className={`badge ${user.role.toLowerCase()}`}>{user.role}</span></td><td><span className={`badge ${user.isActive ? 'active' : 'locked'}`}>{user.isActive ? 'Hoạt động' : 'Đã khóa'}</span></td><td>{new Date(user.createdAt).toLocaleDateString('vi-VN')}</td><td><div className="row-actions"><button title="Xem" aria-label={`Xem ${user.email}`} onClick={() => setViewing(user)}>◉</button><PermissionGate permission="users:write"><button title="Sửa" onClick={() => open(user)}>✎</button><button title="Đặt lại mật khẩu" onClick={() => void resetPassword(user)}>↻</button><button className={user.isActive ? 'warning' : 'success-action'} onClick={() => void toggleLock(user)}>{user.isActive ? 'Khóa' : 'Mở'}</button></PermissionGate><PermissionGate permission="users:delete"><button className="danger" title="Xóa" onClick={() => void remove(user)}>♲</button></PermissionGate></div></td></tr>)}</tbody></table>{!items.length && <p className="empty">Không có người dùng phù hợp.</p>}</div>
    {viewing && <Modal title="Chi tiết người dùng" onClose={() => setViewing(null)}><dl className="profile-details"><div><dt>Mã</dt><dd>{viewing.code}</dd></div><div><dt>Họ và tên</dt><dd>{viewing.fullName}</dd></div><div><dt>Email</dt><dd>{viewing.email}</dd></div><div><dt>Vai trò</dt><dd>{viewing.role}</dd></div><div><dt>Trạng thái</dt><dd>{viewing.isActive ? 'Đang hoạt động' : 'Đã khóa'}</dd></div></dl></Modal>}
    {editing && <Modal title={editing === 'new' ? 'Thêm người dùng' : 'Cập nhật người dùng'} onClose={() => setEditing(null)}><form className="form-grid" onSubmit={submit}><label>Họ và tên<input value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} required minLength={2} maxLength={100} /></label><label>Email<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /></label>{editing === 'new' && <label>Mật khẩu<input type="password" value={form.password || ''} onChange={e => setForm({ ...form, password: e.target.value })} required minLength={8} /></label>}<label>Vai trò<select value={form.role} onChange={e => setForm({ ...form, role: e.target.value as Role })}><option>STUDENT</option><option>ADMIN</option></select></label><label className="check"><input type="checkbox" checked={form.isActive} onChange={e => setForm({ ...form, isActive: e.target.checked })} /> Đang hoạt động</label>{error && <p className="alert error span-2">{error}</p>}<div className="modal-actions span-2"><button type="button" className="secondary-button" onClick={() => setEditing(null)}>Hủy</button><button className="primary-button" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu'}</button></div></form></Modal>}
  </>;
}
